config/routes.rb
Rails.application.routes.draw do
  resources :songs do
	member do
 		put "like", to:    "songs#upvote"
      	put "dislike", to: "songs#downvote"
		put 'play', to: 'songs#play'
	end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'songs#index'	
  match "search" => "songs#search",  via: [:get, :post]
  devise_for :user 
  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/song.rb
class Song < ApplicationRecord
  acts_as_votable  
  belongs_to :user 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, 
         :validatable 
  has_many :songs

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :mobile_device?

  protected
# Get current song playing to display in /index
  def get_current
	if(Rails.application.config.client.status == nil)
		flash[:error] = 'Spotify App Not Connected'
		return
	end
	if(Rails.application.config.client.status['playing'])
		track =  Rails.application.config.client.status['track']['track_resource']['name']
		length = Rails.application.config.client.status['track']['length'] 
		track = Song.find_by_track(track)
		track = {
				id: track.id,
				track: track.track,
				artists: track.artists,
				url: track.url,
				username: track.user.username,
				length: length
		}
		return track
	else
		return  Song.new()
	end
  end

  def check_for_mobile
    session[:mobile_override] = params[:mobile] if params[:mobile]
	prepare_for_mobile if mobile_device?
  end

  def prepare_for_mobile
    prepend_view_path Rails.root + 'app' + 'views_mobile'
  end

  def mobile_device?
    if session[:mobile_override]
      session[:mobile_override] == "1"
    else
      # Season this regexp to taste. I prefer to treat iPad as non-mobile.
      (request.user_agent =~ /Mobile|webOS/) && (request.user_agent !~ /iPad/)
	end
  end

 def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
 end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  # Render mobile or desktop depending on User-Agent for these actions.
  before_action :check_for_mobile, :only => [:show, :index, :new, :edit, :search]
  # Always render mobile versions for these, regardless of User-Agent.
  # before_action :prepare_for_mobile, only: [:show, :index]
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /songs
  # GET /songs.json
  def get_songs
	if @current.nil?
		return Song.order(:cached_votes_up  => :desc)
	else	
		return Song.where.not(id: @current[:id]).order(:cached_votes_up  => :desc)
	end
  end

  def index
	@songs = []
	@current = get_current  
	@songs = get_songs
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = current_user.songs.build(
			:track => params[:track], 
			:album => params[:album], 
			:artists => params[:artists], 
			:uri => params[:uri], 
			:url => params[:url])
	@current = get_current  
	@songs = get_songs
  end

  # GET /songs/1/edit
  def edit
  end

  def find
	 case @search_opt
        when 'Artist'
            @search_res = RSpotify::Artist.search(@search)
    		@search_res = @search_res.first(5) # Returns the first 5 similar artists
        when 'Album'
            @search_res = RSpotify::Album.search(@search)
    		@search_res = @search_res.first(3) # Returns the first 3 similar albums 
        when 'Track'
            @search_res = RSpotify::Track.search(@search) 
    		@search_res = @search_res.first(30) # Returns the first 15 similar track
    	end
		flash[:error]= 'Item Not Found' if !@search_res.any?
		
  end

  def search
	if params[:search].present? 
		@search = params[:search]
		@search_opt = params[:search_opt]
		find if @search != nil
	else
		flash[:error] = "Please give us something to search for!" 
	end
  end

  # POST /songs
  # POST /songs.json
  def create
	job=Delayed::Job.enqueue(Schedule::Player.new) #allows delayed_jobs gem to run the background queue of playing songs
	params[:song][:job_id]=job.id
    @song = current_user.songs.build(song_params)
	respond_to do |format|
    if @song.save
  	   format.html { redirect_to root_path, notice: @song.track+" successfully added."}
    else
       format.html { render :new }
       format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
=begin
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end
=end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
	@song = set_song
	Delayed::Job.find(@song.job_id).destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def upvote
	@song = set_song
	@song.upvote_by current_user
    redirect_back(fallback_location: root_path)
  end

  def downvote
	@song = set_song
	@song.downvote_from current_user
    redirect_back(fallback_location: root_path)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:track, :album, :artists, :uri, :url, :job_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songs_helper.rb
module SongsHelper
	def playTop
	if Rails.application.config.client == nil
        Rails.application.config.client = SpotifyClient::Client.new
    end
	if(Rails.application.config.client.status['playing'])
		puts "No need to get SOng"
	else 
		puts " PLASEAE get otuerh song"
    end 
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
		<head>
				<title>Juke Box</title>
				<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
				<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
				<%= csrf_meta_tags %>
		<% unless @current.nil? %>	<meta http-equiv="refresh" content="<%=@current[:length]%>"/>
			<% end %>

			<% if mobile_device? %>
			<style>
				.nav a{
				font-size: 21px !important;
    				}
			</style>
			<% end %>
		</head>
		<body>
				<header class="navbar navbar-inverse" role="navigation">
						<div class="navbar-inner">
								<div class="container">
										<div id="logo" class="navbar-brand"><%= link_to "Juke Box", root_path %></div>
										<nav class="collapse navbar-collapse navbar-ex1-collapse">
												<% if user_signed_in? %>
														<ul class="nav navbar-nav navbar-right">
																<% if !mobile_device?%> <li><%= link_to 'Submit Song', search_path %></li> <% end %>
																<li><%= link_to 'Account', edit_user_registration_path %></li>
																<li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
														</ul>
												<% else %>
														<ul class="nav navbar-nav pull-right">
																<li><%= link_to 'Sign up', new_user_registration_path %></li>
																<li><%= link_to 'Sign in', new_user_session_path %></li>
														</ul>
												<% end %>
										</nav>
								</div>
						</div>
				</header>
				<div id="main_content" class="container"> 
						<% flash.each do |name, msg| %>
								<%= content_tag(:div, msg, class: "alert alert-info") %>
						<% end %>
						<!-- div id="content" class="col-md-9 center-block" -->
								<%= yield %>
						<!--/div-->
					</div>
				</div>
		</body>
</html>

app/views/songs/_form.html.erb
<div class = 'new'>
<center>
<%= form_for(song) do |f| %>
  <% if song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-group">
    <%= f.label "Track" ,:class => 'form-field'%>
    <%= f.text_field :track, :readonly => true ,:class => 'form-control', :size => '50x10'%>
    <%= f.label "Album" ,:class => 'form-field'%>
    <%= f.text_field :album, :readonly => true, :class => 'form-control'%>
    <%= f.label "Artist" ,:class => 'form-field'%>
    <%= f.text_field :artists, :readonly => true, :class => 'form-control'%>
    <%= f.hidden_field :uri %>
	<%= f.hidden_field :url %>
	<br>
	<br>
    <%= f.submit :submit, class: 'btn btn-success btn-lg'%>
	</center>
<center><%= link_to 'Back', search_path(@song) , :class => "btn btn-default btn-lg" %></center>
</div>
<% end %>
</div>

app/views/songs/index.html.erb
<%= javascript_include_tag "index_player/TweenMax.min.js" ,"data-turbolinks-track" => true %>
<%= javascript_include_tag "index_player/player.js" ,"data-turbolinks-track" => true %>

<style>
html {overflow: -moz-scrollbars-none;}
 body {
	background: #333333 !important;
 }
 </style>
<% unless @current.nil? %>
		<div class="player">
				<div class="player-info">
						<div class="player-info-text">
								<h2 class="player-song-name"><%= @current[:track] %></h2>
								<h3 class="player-artist"><%= @current[:artists] %></h3>
								<h3 class= "player-artist">Submitted by <%= @current[:username]%></h3>
						</div>
						<div class="player-cover">
								<% if @current[:url] != nil %>
								<%= image_tag(@current[:url])%>
								<% end %>
						</div>
				</div>
				<div class="player-spectrum">
						<div class="player-spectrum-bars">
								<div class="player-spectrum-bar"></div>
								<div class="player-spectrum-bar"></div>
								<div class="player-spectrum-bar"></div>
								<div class="player-spectrum-bar"></div>
								<div class="player-spectrum-bar"></div>
								<div class="player-spectrum-bar"></div>
								<div class="player-spectrum-bar"></div>
								<div class="player-spectrum-bar"></div>
								<div class="player-spectrum-bar"></div>
								<div class="player-spectrum-bar"></div>
								<div class="player-spectrum-bar"></div>
								<div class="player-spectrum-bar"></div>
								<div class="player-spectrum-bar"></div>
								<div class="player-spectrum-bar"></div>
								<div class="player-spectrum-bar"></div>
								<div class="player-spectrum-bar"></div>
						</div>
						<div class="player-spectrum-floor"></div>
				</div>
				<div class="player-drops"></div>
		</div>
		<p class="info">Based on the Dribbble shot <a href="https://dribbble.com/shots/1857356-Juicy-Player">Juicy Player</a> by Valentyn Khenkin</p>
		<center>
				<button type="button" id='play-pause' class="btn btn-danger" >Turn off Effect</button>
		</center>
<% end %>
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="800">
		<defs>
		<filter id="goo">
		<feGaussianBlur in="SourceGraphic" stdDeviation="10" result="blur" />
		<feColorMatrix in="blur" mode="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 19 -9" result="goo" />
		<feComposite in="SourceGraphic" in2="goo" operator="atop"/>
		</filter>
		<filter id="goo-no-comp">
		<feGaussianBlur in="SourceGraphic" stdDeviation="10" result="blur" />
		<feColorMatrix in="blur" mode="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 20 -9" result="goo" />
		</filter>
		<filter id="goo-drops">
		<feGaussianBlur in="SourceGraphic" stdDeviation="6" result="blur" />
		<feColorMatrix in="blur" mode="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 19 -9" result="goo" />
		</filter>
		</defs>
</svg>
<center>
		<% @songs.each do |song| %>
				<div class="song row clearfix">
						<h2>
								<%= song.track %><br>
								<%= song.artists %><br>
								<%= image_tag(song.url) %><br>
								<small class="author">Submitted <%= time_ago_in_words(song.created_at) %> by <%= song.user.username %></small></br>
						<div class="btn-group">
							<span class="btn btn-default btn-clg"> <%= song.get_upvotes.size %></span>
								<%= link_to like_song_path(song), method: :put, class: "btn btn-default btn-clg" do %>
										<span class="glyphicon glyphicon-chevron-up"></span> Up
										<%#= song.votes_for.size %>
								<% end %>
								<%= link_to dislike_song_path(song), method: :put, class: "btn btn-default btn-clg" do %>
										<span class="glyphicon glyphicon-chevron-down"></span> Down
												<%#= song.get_downvotes.size %>
										<% end %>
										<%#= link_to "Show",song, class: "btn btn-default btn-lg" %>
										<% if song.user == current_user %>
												<%= link_to 'Delete', song, method: :delete, data: { confirm:'Are you sure?' } , class: "btn btn-default btn-clg"%>
										<% end %>

						</div>
				</div>
		<% end %>
</center>
<script>
$("#play-pause").click(function(){
		window.play();
});
</script>
</div>

app/views/songs/new.html.erb
<div class="row">
<div class="col-xs-4"> 
	<h1> Current Playing </h1>
		<p> <%=@current[:track]%> - <%=@current[:artists]%> </p>
	<h2>Current Queue</h2>
	<% if @songs != nil %>
		<% @songs.each do |song| %>
			<p> <%= song.track %> - <%= song.artists %><p>
		<% end %>
	<% end %>
</div>
<div class="col-xs-8">
      <div class="row">
        <div class="col col-md-">
			<%= image_tag(@song.url, class: "picture-new") %>
			<%= render 'form', song: @song %>
		</div>
      </div>
</div>
<%#= link_to 'Back', search_path(@song) , :class => "btn btn-default" %>

app/views/songs/search.html.erb
<%= javascript_include_tag "search/modernizr.custom.js" ,"data-turbolinks-track" => true %>
<div id="content" class="col-sm-8 center-block">
<h1> Search</h1>
<%= form_tag(search_path, :method => "get", id: "search-form") do %>
		<div class="input-group">
				<%= text_field_tag 'search', params[:search], placeholder: "Search Tracks" , class: 'form-control' %>
				<span class="input-group-btn">
						<%= select_tag "search_opt",options_for_select(["Track","Album","Artist"],selected: 'Track'), class: 'form-control', style: "width:auto"%>
						<%= submit_tag "submit",class: "btn btn-danger",  'data-disable-with' => "Please wait.." %>
				</span>
		</div>
<% end %>
</div>
<div id ="ImagesGrid">
<ul class="grid effect-8" id="grid">
		<%case @search_opt %>
		<%when 'Artist'%>
				<% @search_res.each do |res| %>
						<li>
								<h1> <%= res.name %> </h1>
						</li>
						<% res.top_tracks(:US).each do |track| %>
								<li>
										<%= link_to image_tag(track.album.images.first["url"], size: "350" ),
										new_song_path(:track => track.name, 
													  :album => track.album.name, 
												  	  :artists => track.artists.first.name, 
													  :uri => track.uri,
													  :url => track.album.images.first["url"]) %> 
										<h3> <%= track.name%> </h3>
								</li>
						<% end %>
				<% end %>
		<%when 'Album'%>
				<% @search_res.each do |res| %>
						<li>
								<h1> <%= res.name %> </h1>
						</li>
						<% res.tracks.each do |track| %>
								<li>
										<%= link_to image_tag(track.album.images.first["url"], size: "350" ),
										new_song_path(:track => track.name, 
													  :album => track.album.name, 
												  	  :artists => track.artists.first.name, 
													  :uri => track.uri,
													  :url => track.album.images.first["url"]) %> 
										<h3> <%= track.name%> </h3>
								</li>
						<% end %>
				<% end %>
		<%when 'Track'%>
				<% @search_res.each do |track| %>
						<li>
								<%= link_to image_tag(track.album.images.first["url"], size: "400" ),
									new_song_path(:track => track.name, 
												  :album => track.album.name, 
												  :artists => track.artists.first.name, 
												  :uri => track.uri, 
												  :url => track.album.images.first["url"]) %> 
								<h2><%= track.name%></h2> 
						</li>
				<% end %>
		<% end %>
</ul>
</div>
<p class="info">Based on the <a href="https://tympanus.net/Development/GridLoadingEffects/">Loading Effects for Grid Items</a> by Erika Mackley</p>
<%= javascript_include_tag "search/masonry.pkgd.min.js" ,"data-turbolinks-track" => true %>
<%= javascript_include_tag "search/imagesloaded.js" ,"data-turbolinks-track" => true %>
<%= javascript_include_tag "search/classie.js" ,"data-turbolinks-track" => true %>
<%= javascript_include_tag "search/AnimOnScroll.js" ,"data-turbolinks-track" => true %>
<script>
$("#ImagesGrid").hide();
new AnimOnScroll( document.getElementById( 'grid' ), {
		minDuration : 0.4,
		maxDuration : 0.6,
		viewportFactor : 0.2
} );
$('#container').imagesLoaded( function() {
	console.log("ImagesLoaded");
	$("#ImagesGrid").show();
});

</script>

app/views/songs/show.html.erb
<center>
<%= image_tag(@song.url) %>
<div class= 'lead'>
<p class='text-center'>
<%= @song.track %>
</p>
<p class= 'text-center'>
<%= @song.album %>
</p>
<p class = 'text-center'>
<%= @song.artists %>
</p>
</div>
<h1 class ='text-center'><%= link_to 'Edit', edit_song_path(@song), class: "btn btn-danger btn-lg" %></h1>
<h1 class = 'text-center'><%= link_to 'Home',root_path, class:"btn btn-success btn-lg" %></h1>
</center>